# Numpy
- Neden Numpy?
    - Çünkü Numpy sayesinde hızlı nümerik işlemler yapabiliriz.
- C, C++ gibi makine diline yakın diller Python'dan daha hızlıdır. C dilinde yazılan Numpy kütüphanesi Python dilinde daha hızlı nümerik işlemler yapmamızı sağlar.

## Numpy Array
- Numpy array, Python'daki list'lerden tek farkı farklı veri tipinde eleman içeremez. Array içinde ki veri tipi tamamiyle aynı olmalıdır.

### Listeden Array yaratmak

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [3]:
type(x)

numpy.ndarray

- Bir array'a hem str hem de int verirsek, hata vermez fakat hepsini str'ye çevirir.

In [4]:
y = np.array(["a","b",1,2,"c"])
y

array(['a', 'b', '1', '2', 'c'], dtype='<U11')

- Bir array'a hem float hem de int verirsek, bütün sayıları float'a dönüstürür.

In [5]:
z = np.array([1,2,3,4.5,5.6,6,7])
z

array([1. , 2. , 3. , 4.5, 5.6, 6. , 7. ])

- Bu durumda bir array için str>float>int gibi dusunebiliriz.

## Array'in Data Tipini Belirleme
- Array'in elemanlarının tipinin ne olacağını manuel olarak belirleyebiliriz.

In [6]:
x = np.array([1,2,3,4.5], dtype="int32")
x

array([1, 2, 3, 4])

- dtype= ".." keyword'ü ile istediğimiz dönüsümü gerceklestirebiliriz

In [7]:
z = np.array([1,2,3,4,5], dtype="str")
z

array(['1', '2', '3', '4', '5'], dtype='<U1')

## Elemanları 0'dan oluşan bir array oluşturmak

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- veri tipi belirtmediğimiz takdirde float olarak oluşturur.

In [9]:
np.zeros(10, dtype="str")

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

## Elemanları 0'dan oluşan multidimensional array oluşturmak

- elemanları 0, 3 satır ve 4 sütunu olan bir array oluşturmak istersek

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros([3,4], dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.zeros([3,4], dtype="bool")

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [13]:
np.zeros([3,4,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Belirtilen Bir Elemandan Array Oluşturmak

In [14]:
np.full((4,5) ,5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

- np.full( (x, y), z) fonksiyonundaki inputlar x,y büyüklüğünde elemanları z olur.

- veri olarak sadece int girmek zorunda değiliz

In [15]:
np.full( (4,5), "a")

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

- 3. input olarak veri tipi de girebiliriz

In [16]:
np.full( (3,4) , 5.2, dtype="str")

array([['5', '5', '5', '5'],
       ['5', '5', '5', '5'],
       ['5', '5', '5', '5']], dtype='<U1')

- fakat float bir değeri str'ye dönüştürürken ilk olarak int'e dönüştürür.
- eğer str olarak bir float girmek istersek asagidaki sekilde girmemiz gerekir.

In [17]:
np.full( (4,5), "5.2")

array([['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2']], dtype='<U3')

## Ardaşık Sayılardan Array Oluşturmak

- 0'dan 12'ye kadar sayılardan array oluşturmak istersek

In [18]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- 2'şer artırarak sayıları almak istersek

In [19]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Aralığı Eşit Uzaklıktaki Noktalara Bölmek

- Örneğin 1 ve 2 arasını (1 ve 2 dahil) eşit uzaklıkta 50 noktaya bölmek istersek:

In [20]:
- np.linspace(1,2)

array([-1.        , -1.02040816, -1.04081633, -1.06122449, -1.08163265,
       -1.10204082, -1.12244898, -1.14285714, -1.16326531, -1.18367347,
       -1.20408163, -1.2244898 , -1.24489796, -1.26530612, -1.28571429,
       -1.30612245, -1.32653061, -1.34693878, -1.36734694, -1.3877551 ,
       -1.40816327, -1.42857143, -1.44897959, -1.46938776, -1.48979592,
       -1.51020408, -1.53061224, -1.55102041, -1.57142857, -1.59183673,
       -1.6122449 , -1.63265306, -1.65306122, -1.67346939, -1.69387755,
       -1.71428571, -1.73469388, -1.75510204, -1.7755102 , -1.79591837,
       -1.81632653, -1.83673469, -1.85714286, -1.87755102, -1.89795918,
       -1.91836735, -1.93877551, -1.95918367, -1.97959184, -2.        ])

- Burada kaç nokta olduğunu vermezsek default olarak 50'ye böler
- Eğer istediğimiz kadar aralığa bölmek istersek başlangıc ve bitis noktasından sonra num=x olarak istediğimiz kadar aralığa bölebiliriz

In [21]:
np.linspace(1,2, num=3)

array([1. , 1.5, 2. ])

- Normalde default olarak bitis elemanını da dahil eder. ama istersek endpoint = false ile bitiş noktasını dahil etmeyebiliriz

In [22]:
np.linspace(1,2, num=3, endpoint=False)

array([1.        , 1.33333333, 1.66666667])

## Normal Distribution'dan Çekilmiş Değerlerden Array Oluşturmak

- np.random.normal(mean, standart_sapma, (array_size)) ile bir array oluşturabiliriz


In [23]:
np.random.normal(0,1, (3,4))

array([[ 0.17954551,  1.05397776,  0.35588695,  2.10179951],
       [ 2.4777745 ,  0.20292863, -0.18682339, -0.38465658],
       [ 1.35597941, -1.72066835, -1.08174059, -1.74620399]])

In [24]:
np.random.normal(0,100, (3,4))

array([[-126.31473724,  137.09859176,   92.25607809,  -42.38687491],
       [-207.32318786,  -68.31401232,   64.52617268,   97.03906809],
       [ -82.08950817,   73.56664117,   24.28959471,  -84.05000124]])

## Random int'lar ile array oluşturmak

- np.random.randint(baslangic, bitis, (array_size)) ile istenilen aralıkta istenilen boyutta arraylar üretebiliriz. 
- bitis bu aralığa dahil değildir

In [25]:
np.random.randint(1,10, (3,4))

array([[3, 3, 5, 8],
       [8, 6, 1, 5],
       [4, 9, 3, 2]])

In [26]:
np.random.randint(1,10, (3,4,5))

array([[[4, 8, 8, 5, 8],
        [9, 4, 8, 9, 9],
        [1, 3, 5, 5, 4],
        [7, 3, 5, 5, 2]],

       [[2, 2, 1, 3, 7],
        [6, 4, 5, 5, 9],
        [4, 4, 1, 9, 9],
        [2, 9, 1, 9, 2]],

       [[7, 2, 7, 9, 7],
        [3, 4, 3, 8, 1],
        [1, 7, 4, 7, 7],
        [6, 7, 7, 4, 7]]])

In [27]:
d = {}

for _ in range (20000):
    val = np.random.randint(1,11)    
    if val not in d:
        d[val] = 1
    else:
        d[val] += 1
        
d

{1: 1999,
 5: 1966,
 10: 1901,
 6: 1972,
 2: 2053,
 3: 2035,
 4: 2058,
 9: 2055,
 7: 2005,
 8: 1956}

## Identity (Birim) Matris Oluşturmak

- Bir birim matrisi oluşturmak için np.eye(x,y) fonksiyonunu kullanırız


In [28]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [29]:
np.eye(3,3, dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Array İşlemleri

- "*" operatörü iki list arasında tanımsızdır. iki listeyi * ile çarpamayız

In [30]:
a = [1,2,3,4,5]
b = [2,3,4,5,6]

a*b

<class 'TypeError'>: can't multiply sequence by non-int of type 'list'

- Bir list'i bir int ile çarparsak o int kadar listeyi yanyana yazar. sayısal bir çarpma işlemi gerçekleştirmez

In [31]:
[2,3,4,5] * 3

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]

- Fakat * operatörü iki numpy arasında işlem gerceklestirebilir. eleman bazlı carpma yapabilir.
- Bu 2 numpy arrayin eleman sayisi ayni olmalidir.

In [32]:
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])

a*b

array([ 2,  6, 12, 20, 30])

- Aynı şekilde list + list islemi yaptıgımızda concatination işlemi yaparken, array + array işleminde eleman bazlı toplama yapılır.

In [33]:
a + b

array([ 3,  5,  7,  9, 11])

- Bir int ile bir arrayi çarptigimizda da eleman bazlı carpma işlemi gerçekleştirilir.

In [34]:
print("a: ", a)
print("a * 3: ", 3*a)

a:  [1 2 3 4 5]
a * 3:  [ 3  6  9 12 15]


## Array Attributes

- XX.shape ile bir matrisin satır ve sütun sayılarını bulabiliriz.

In [35]:
x = np.zeros((2,3), dtype="int")
x

array([[0, 0, 0],
       [0, 0, 0]])

In [36]:
y = np.zeros((2,5,4), dtype="int")
y

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [37]:
x.shape

(2, 3)

In [38]:
y.shape

(2, 5, 4)

- XX.ndim ise o matrisin kaç dimension'a sahip olduğunu gösterir. Örneğin:

In [39]:
x.ndim

2

In [40]:
y.ndim

3

- XX.size ise o matrisin kaç elemanlı olduğunu döndürür.

In [41]:
x.size

6

In [42]:
y.size

40

- XX.dtype o matrisin veri tipini gösterir.

In [43]:
x.dtype

dtype('int32')

## Bir Arrayi Yeniden Şekillendirmek

- Bir arrayi reshape yaptıktan sonra sadece şekli değişecektir, boyut olarak kesinlikle aynı kalır.

In [44]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
print("a.ndim: ", a.ndim)
print("a.size: ", a.size)

a.ndim:  1
a.size:  10


- Eğer a'yi 2 satir 5 sütun içeren bir matrise çevirmek istersek:

In [50]:
a = a.reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
print("a.ndim: ", a.ndim)
print("a.size: ", a.size)

a.ndim:  2
a.size:  10


- Görüleceği üzere matrisin boyutu aynı kalmiştir.

- Eğer ki eleman sayısı ve satır-sütun sayısı tutarsız olursa hata verecektir.

In [53]:
a.reshape(6,2)
# 6x2 = 12 yapar. fakat bizim 10 elemanımız var.

<class 'ValueError'>: cannot reshape array of size 10 into shape (6,2)

- eğer ki reshape(x,y)'de x yerine -1 yazarsak, fonksiyon otomatik olarak y'ye ve boyuta göre x'i bulacaktır.

In [55]:
a = a.reshape(-1, 2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

- Yukarıda matrisin satir sayısını sütun sayısı=2'ye göre ayarlamıştır

### Matrise Yeni Bir Boyut Eklemek

In [61]:
xx = np.arange(1,11)
xx

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
xx.shape

(10,)

In [65]:
xx = xx[np.newaxis, :]

In [66]:
xx.shape

(1, 10)

In [69]:
xx = np.arange(1,11)

In [70]:
xx = xx[:, np.newaxis]

In [71]:
xx.shape

(10, 1)

In [76]:
xx = np.arange(1,11)

In [77]:
xx = xx[None, :]
xx

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [78]:
xx.size

10

## Array'lerde Concatenation

- iki tane arrayi birleştirirken np.concatenate() fonksiyonunu kullanrız.

In [79]:
a = np.array([1,2,3,4])

In [80]:
b = np.array([5,6,7,8])

In [82]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

- python listlerini de arrayleri ile birleştirebiliriz.

In [83]:
l = [10,11]

In [84]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

- fakat listede hem int hemde float eleman varsa arraylerin elemanlarını float yapacaktır.
- veya listede str varsa arrayin elemanlarını da str yapar.

In [87]:
l = [10, 11, 11.2]

In [88]:
np.concatenate([a,b,l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. , 10. , 11. , 11.2])

- eğer ki np.concatenate([x,y], axis=1) olarak bir input verecek olursak;

In [90]:
x = np.array([[1,2,3],[4,5,6]])

In [91]:
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [92]:
np.concatenate([x,x], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- burada axis = 0 (default deger) alt alta ekleyecektir. 
- Fakat axis = 1 dersek, yanyana koyacaktir.