# Numpy
- Neden Numpy?
    - Çünkü Numpy sayesinde hızlı nümerik işlemler yapabiliriz.
- C, C++ gibi makine diline yakın diller Python'dan daha hızlıdır. C dilinde yazılan Numpy kütüphanesi Python dilinde daha hızlı nümerik işlemler yapmamızı sağlar.

## Numpy Array
- Numpy array, Python'daki list'lerden tek farkı farklı veri tipinde eleman içeremez. Array içinde ki veri tipi tamamiyle aynı olmalıdır.

### Listeden Array yaratmak

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [3]:
type(x)

numpy.ndarray

- Bir array'a hem str hem de int verirsek, hata vermez fakat hepsini str'ye çevirir.

In [4]:
y = np.array(["a","b",1,2,"c"])
y

array(['a', 'b', '1', '2', 'c'], dtype='<U11')

- Bir array'a hem float hem de int verirsek, bütün sayıları float'a dönüstürür.

In [5]:
z = np.array([1,2,3,4.5,5.6,6,7])
z

array([1. , 2. , 3. , 4.5, 5.6, 6. , 7. ])

- Bu durumda bir array için str>float>int gibi dusunebiliriz.

## Array'in Data Tipini Belirleme
- Array'in elemanlarının tipinin ne olacağını manuel olarak belirleyebiliriz.

In [6]:
x = np.array([1,2,3,4.5], dtype="int32")
x

array([1, 2, 3, 4])

- dtype= ".." keyword'ü ile istediğimiz dönüsümü gerceklestirebiliriz

In [7]:
z = np.array([1,2,3,4,5], dtype="str")
z

array(['1', '2', '3', '4', '5'], dtype='<U1')

## Elemanları 0'dan oluşan bir array oluşturmak

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- veri tipi belirtmediğimiz takdirde float olarak oluşturur.

In [9]:
np.zeros(10, dtype="str")

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

## Elemanları 0'dan oluşan multidimensional array oluşturmak

- elemanları 0, 3 satır ve 4 sütunu olan bir array oluşturmak istersek

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros([3,4], dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.zeros([3,4], dtype="bool")

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [13]:
np.zeros([3,4,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Belirtilen Bir Elemandan Array Oluşturmak

In [15]:
np.full((4,5) ,5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

- np.full( (x, y), z) fonksiyonundaki inputlar x,y büyüklüğünde elemanları z olur.

- veri olarak sadece int girmek zorunda değiliz

In [17]:
np.full( (4,5), "a")

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

- 3. input olarak veri tipi de girebiliriz

In [20]:
np.full( (3,4) , 5.2, dtype="str")

array([['5', '5', '5', '5'],
       ['5', '5', '5', '5'],
       ['5', '5', '5', '5']], dtype='<U1')

- fakat float bir değeri str'ye dönüştürürken ilk olarak int'e dönüştürür.
- eğer str olarak bir float girmek istersek asagidaki sekilde girmemiz gerekir.

In [21]:
np.full( (4,5), "5.2")

array([['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2']], dtype='<U3')

## Ardaşık Sayılardan Array Oluşturmak

- 0'dan 12'ye kadar sayılardan array oluşturmak istersek

In [24]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- 2'şer artırarak sayıları almak istersek

In [28]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Aralığı Eşit Uzaklıktaki Noktalara Bölmek

- Örneğin 1 ve 2 arasını (1 ve 2 dahil) eşit uzaklıkta 50 noktaya bölmek istersek:

In [31]:
- np.linspace(1,2)

array([-1.        , -1.02040816, -1.04081633, -1.06122449, -1.08163265,
       -1.10204082, -1.12244898, -1.14285714, -1.16326531, -1.18367347,
       -1.20408163, -1.2244898 , -1.24489796, -1.26530612, -1.28571429,
       -1.30612245, -1.32653061, -1.34693878, -1.36734694, -1.3877551 ,
       -1.40816327, -1.42857143, -1.44897959, -1.46938776, -1.48979592,
       -1.51020408, -1.53061224, -1.55102041, -1.57142857, -1.59183673,
       -1.6122449 , -1.63265306, -1.65306122, -1.67346939, -1.69387755,
       -1.71428571, -1.73469388, -1.75510204, -1.7755102 , -1.79591837,
       -1.81632653, -1.83673469, -1.85714286, -1.87755102, -1.89795918,
       -1.91836735, -1.93877551, -1.95918367, -1.97959184, -2.        ])

- Burada kaç nokta olduğunu vermezsek default olarak 50'ye böler
- Eğer istediğimiz kadar aralığa bölmek istersek başlangıc ve bitis noktasından sonra num=x olarak istediğimiz kadar aralığa bölebiliriz

In [33]:
np.linspace(1,2, num=3)

array([1. , 1.5, 2. ])

- Normalde default olarak bitis elemanını da dahil eder. ama istersek endpoint = false ile bitiş noktasını dahil etmeyebiliriz

In [34]:
np.linspace(1,2, num=3, endpoint=False)

array([1.        , 1.33333333, 1.66666667])

## Normal Distribution'dan Çekilmiş Değerlerden Array Oluşturmak

- np.random.normal(mean, standart_sapma, (array_size)) ile bir array oluşturabiliriz


In [37]:
np.random.normal(0,1, (3,4))

array([[ 0.8799111 , -0.96502188, -1.36710957,  1.05824521],
       [-0.86366259,  0.3273051 , -0.21854387, -0.90252949],
       [ 1.09653177, -0.27735361, -0.32352746,  0.40580242]])

In [39]:
np.random.normal(0,100, (3,4))

array([[-129.59705803,   53.17985858,   67.47072588,  111.46222632],
       [ 100.8285207 ,  229.43651742,  141.09924618,   53.86964642],
       [  74.1017428 ,  -72.02140617,   16.89580472,   52.31436945]])

## Random int'lar ile array oluşturmak

- np.random.randint(baslangic, bitis, (array_size)) ile istenilen aralıkta istenilen boyutta arraylar üretebiliriz. 
- bitis bu aralığa dahil değildir

In [44]:
np.random.randint(1,10, (3,4))

array([[3, 9, 3, 4],
       [8, 2, 6, 8],
       [2, 4, 4, 7]])

In [46]:
np.random.randint(1,10, (3,4,5))

array([[[8, 3, 4, 8, 5],
        [2, 5, 8, 2, 8],
        [8, 6, 5, 4, 8],
        [7, 3, 1, 2, 8]],

       [[2, 6, 1, 5, 1],
        [8, 2, 5, 7, 6],
        [1, 3, 7, 4, 2],
        [9, 8, 7, 4, 6]],

       [[3, 4, 6, 2, 8],
        [8, 7, 8, 6, 5],
        [7, 8, 7, 2, 3],
        [8, 8, 2, 2, 1]]])

In [55]:
d = {}

for _ in range (20000):
    val = np.random.randint(1,11)    
    if val not in d:
        d[val] = 1
    else:
        d[val] += 1
        
d

{6: 1985,
 3: 2011,
 8: 2170,
 4: 1916,
 9: 1915,
 1: 2046,
 2: 1956,
 10: 2037,
 5: 2004,
 7: 1960}

## Identity (Birim) Matris Oluşturmak

- Bir birim matrisi oluşturmak için np.eye(x,y) fonksiyonunu kullanırız


In [56]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [58]:
np.eye(3,3, dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Array İşlemleri

- "*" operatörü iki list arasında tanımsızdır. iki listeyi * ile çarpamayız

In [62]:
a = [1,2,3,4,5]
b = [2,3,4,5,6]

a*b

<class 'TypeError'>: can't multiply sequence by non-int of type 'list'

- Bir list'i bir int ile çarparsak o int kadar listeyi yanyana yazar. sayısal bir çarpma işlemi gerçekleştirmez

In [63]:
[2,3,4,5] * 3

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]

- Fakat * operatörü iki numpy arasında işlem gerceklestirebilir. eleman bazlı carpma yapabilir.
- Bu 2 numpy arrayin eleman sayisi ayni olmalidir.

In [65]:
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])

a*b

array([ 2,  6, 12, 20, 30])

- Aynı şekilde list + list islemi yaptıgımızda concatination işlemi yaparken, array + array işleminde eleman bazlı toplama yapılır.

In [68]:
a + b

array([ 3,  5,  7,  9, 11])

- Bir int ile bir arrayi çarptigimizda da eleman bazlı carpma işlemi gerçekleştirilir.

In [70]:
print("a: ", a)
print("a * 3: ", 3*a)

a:  [1 2 3 4 5]
a * 3:  [ 3  6  9 12 15]


## Array Attributes

- XX.shape ile bir matrisin satır ve sütun sayılarını bulabiliriz.

In [73]:
x = np.zeros((2,3), dtype="int")
x

array([[0, 0, 0],
       [0, 0, 0]])

In [75]:
y = np.zeros((2,5,4), dtype="int")
y

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [76]:
x.shape

(2, 3)

In [77]:
y.shape

(2, 5, 4)

- XX.ndim ise o matrisin kaç dimension'a sahip olduğunu gösterir. Örneğin:

In [80]:
x.ndim

2

In [81]:
y.ndim

3

- XX.size ise o matrisin kaç elemanlı olduğunu döndürür.

In [82]:
x.size

6

In [83]:
y.size

40

- XX.dtype o matrisin veri tipini gösterir.

In [85]:
x.dtype

dtype('int32')