# Numpy
- Neden Numpy?
    - Çünkü Numpy sayesinde hızlı nümerik işlemler yapabiliriz.
- C, C++ gibi makine diline yakın diller Python'dan daha hızlıdır. C dilinde yazılan Numpy kütüphanesi Python dilinde daha hızlı nümerik işlemler yapmamızı sağlar.

## Numpy Array
- Numpy array, Python'daki list'lerden tek farkı farklı veri tipinde eleman içeremez. Array içinde ki veri tipi tamamiyle aynı olmalıdır.

### Listeden Array yaratmak

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [3]:
type(x)

numpy.ndarray

- Bir array'a hem str hem de int verirsek, hata vermez fakat hepsini str'ye çevirir.

In [4]:
y = np.array(["a","b",1,2,"c"])
y

array(['a', 'b', '1', '2', 'c'], dtype='<U11')

- Bir array'a hem float hem de int verirsek, bütün sayıları float'a dönüstürür.

In [5]:
z = np.array([1,2,3,4.5,5.6,6,7])
z

array([1. , 2. , 3. , 4.5, 5.6, 6. , 7. ])

- Bu durumda bir array için str>float>int gibi dusunebiliriz.

## Array'in Data Tipini Belirleme
- Array'in elemanlarının tipinin ne olacağını manuel olarak belirleyebiliriz.

In [6]:
x = np.array([1,2,3,4.5], dtype="int32")
x

array([1, 2, 3, 4])

- dtype= ".." keyword'ü ile istediğimiz dönüsümü gerceklestirebiliriz

In [7]:
z = np.array([1,2,3,4,5], dtype="str")
z

array(['1', '2', '3', '4', '5'], dtype='<U1')

## Elemanları 0'dan oluşan bir array oluşturmak

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- veri tipi belirtmediğimiz takdirde float olarak oluşturur.

In [9]:
np.zeros(10, dtype="str")

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

## Elemanları 0'dan oluşan multidimensional array oluşturmak

- elemanları 0, 3 satır ve 4 sütunu olan bir array oluşturmak istersek

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros([3,4], dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.zeros([3,4], dtype="bool")

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [13]:
np.zeros([3,4,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Belirtilen Bir Elemandan Array Oluşturmak

In [14]:
np.full((4,5) ,5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

- np.full( (x, y), z) fonksiyonundaki inputlar x,y büyüklüğünde elemanları z olur.

- veri olarak sadece int girmek zorunda değiliz

In [15]:
np.full( (4,5), "a")

array([['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a'],
       ['a', 'a', 'a', 'a', 'a']], dtype='<U1')

- 3. input olarak veri tipi de girebiliriz

In [16]:
np.full( (3,4) , 5.2, dtype="str")

array([['5', '5', '5', '5'],
       ['5', '5', '5', '5'],
       ['5', '5', '5', '5']], dtype='<U1')

- fakat float bir değeri str'ye dönüştürürken ilk olarak int'e dönüştürür.
- eğer str olarak bir float girmek istersek asagidaki sekilde girmemiz gerekir.

In [17]:
np.full( (4,5), "5.2")

array([['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2']], dtype='<U3')

## Ardaşık Sayılardan Array Oluşturmak

- 0'dan 12'ye kadar sayılardan array oluşturmak istersek

In [18]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- 2'şer artırarak sayıları almak istersek

In [19]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Aralığı Eşit Uzaklıktaki Noktalara Bölmek

- Örneğin 1 ve 2 arasını (1 ve 2 dahil) eşit uzaklıkta 50 noktaya bölmek istersek:

In [20]:
- np.linspace(1,2)

array([-1.        , -1.02040816, -1.04081633, -1.06122449, -1.08163265,
       -1.10204082, -1.12244898, -1.14285714, -1.16326531, -1.18367347,
       -1.20408163, -1.2244898 , -1.24489796, -1.26530612, -1.28571429,
       -1.30612245, -1.32653061, -1.34693878, -1.36734694, -1.3877551 ,
       -1.40816327, -1.42857143, -1.44897959, -1.46938776, -1.48979592,
       -1.51020408, -1.53061224, -1.55102041, -1.57142857, -1.59183673,
       -1.6122449 , -1.63265306, -1.65306122, -1.67346939, -1.69387755,
       -1.71428571, -1.73469388, -1.75510204, -1.7755102 , -1.79591837,
       -1.81632653, -1.83673469, -1.85714286, -1.87755102, -1.89795918,
       -1.91836735, -1.93877551, -1.95918367, -1.97959184, -2.        ])

- Burada kaç nokta olduğunu vermezsek default olarak 50'ye böler
- Eğer istediğimiz kadar aralığa bölmek istersek başlangıc ve bitis noktasından sonra num=x olarak istediğimiz kadar aralığa bölebiliriz

In [21]:
np.linspace(1,2, num=3)

array([1. , 1.5, 2. ])

- Normalde default olarak bitis elemanını da dahil eder. ama istersek endpoint = false ile bitiş noktasını dahil etmeyebiliriz

In [22]:
np.linspace(1,2, num=3, endpoint=False)

array([1.        , 1.33333333, 1.66666667])

## Normal Distribution'dan Çekilmiş Değerlerden Array Oluşturmak

- np.random.normal(mean, standart_sapma, (array_size)) ile bir array oluşturabiliriz


In [23]:
np.random.normal(0,1, (3,4))

array([[ 2.42383672, -1.25001334, -0.43805976,  0.38629643],
       [-1.46016405,  0.10980051, -0.94459412, -1.26719909],
       [ 0.18740502, -1.48496386, -0.61698618,  1.38995633]])

In [24]:
np.random.normal(0,100, (3,4))

array([[  97.79814043, -154.63716277,   -3.42728442,  -91.01337272],
       [  -7.54077422,   85.88774328,  -19.63533122,  153.42454262],
       [ -38.06479761, -111.53850718,  -94.6930374 ,  -17.60464578]])

## Random int'lar ile array oluşturmak

- np.random.randint(baslangic, bitis, (array_size)) ile istenilen aralıkta istenilen boyutta arraylar üretebiliriz. 
- bitis bu aralığa dahil değildir

In [25]:
np.random.randint(1,10, (3,4))

array([[8, 1, 7, 5],
       [5, 5, 7, 5],
       [5, 4, 5, 3]])

In [26]:
np.random.randint(1,10, (3,4,5))

array([[[4, 5, 8, 3, 8],
        [2, 6, 7, 2, 7],
        [9, 5, 1, 9, 7],
        [1, 4, 8, 2, 6]],

       [[4, 9, 7, 7, 2],
        [3, 9, 7, 7, 4],
        [1, 6, 9, 6, 9],
        [5, 5, 8, 9, 5]],

       [[9, 4, 3, 6, 2],
        [5, 8, 4, 8, 5],
        [4, 4, 6, 6, 3],
        [3, 6, 4, 2, 3]]])

In [27]:
d = {}

for _ in range (20000):
    val = np.random.randint(1,11)    
    if val not in d:
        d[val] = 1
    else:
        d[val] += 1
        
d

{3: 2041,
 8: 2132,
 2: 2007,
 4: 1953,
 10: 1974,
 7: 2031,
 5: 1996,
 9: 1920,
 1: 1967,
 6: 1979}

## Identity (Birim) Matris Oluşturmak

- Bir birim matrisi oluşturmak için np.eye(x,y) fonksiyonunu kullanırız


In [28]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [29]:
np.eye(3,3, dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Array İşlemleri

- "*" operatörü iki list arasında tanımsızdır. iki listeyi * ile çarpamayız

In [30]:
a = [1,2,3,4,5]
b = [2,3,4,5,6]

a*b

<class 'TypeError'>: can't multiply sequence by non-int of type 'list'

- Bir list'i bir int ile çarparsak o int kadar listeyi yanyana yazar. sayısal bir çarpma işlemi gerçekleştirmez

In [31]:
[2,3,4,5] * 3

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]

- Fakat * operatörü iki numpy arasında işlem gerceklestirebilir. eleman bazlı carpma yapabilir.
- Bu 2 numpy arrayin eleman sayisi ayni olmalidir.

In [32]:
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])

a*b

array([ 2,  6, 12, 20, 30])

- Aynı şekilde list + list islemi yaptıgımızda concatination işlemi yaparken, array + array işleminde eleman bazlı toplama yapılır.

In [33]:
a + b

array([ 3,  5,  7,  9, 11])

- Bir int ile bir arrayi çarptigimizda da eleman bazlı carpma işlemi gerçekleştirilir.

In [34]:
print("a: ", a)
print("a * 3: ", 3*a)

a:  [1 2 3 4 5]
a * 3:  [ 3  6  9 12 15]


## Array Attributes

- XX.shape ile bir matrisin satır ve sütun sayılarını bulabiliriz.

In [35]:
x = np.zeros((2,3), dtype="int")
x

array([[0, 0, 0],
       [0, 0, 0]])

In [36]:
y = np.zeros((2,5,4), dtype="int")
y

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [37]:
x.shape

(2, 3)

In [38]:
y.shape

(2, 5, 4)

- XX.ndim ise o matrisin kaç dimension'a sahip olduğunu gösterir. Örneğin:

In [39]:
x.ndim

2

In [40]:
y.ndim

3

- XX.size ise o matrisin kaç elemanlı olduğunu döndürür.

In [41]:
x.size

6

In [42]:
y.size

40

- XX.dtype o matrisin veri tipini gösterir.

In [43]:
x.dtype

dtype('int32')

## Bir Arrayi Yeniden Şekillendirmek

- Bir arrayi reshape yaptıktan sonra sadece şekli değişecektir, boyut olarak kesinlikle aynı kalır.

In [44]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
print("a.ndim: ", a.ndim)
print("a.size: ", a.size)

a.ndim:  1
a.size:  10


- Eğer a'yi 2 satir 5 sütun içeren bir matrise çevirmek istersek:

In [46]:
a = a.reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [47]:
print("a.ndim: ", a.ndim)
print("a.size: ", a.size)

a.ndim:  2
a.size:  10


- Görüleceği üzere matrisin boyutu aynı kalmiştir.

- Eğer ki eleman sayısı ve satır-sütun sayısı tutarsız olursa hata verecektir.

In [48]:
a.reshape(6,2)
# 6x2 = 12 yapar. fakat bizim 10 elemanımız var.

<class 'ValueError'>: cannot reshape array of size 10 into shape (6,2)

- eğer ki reshape(x,y)'de x yerine -1 yazarsak, fonksiyon otomatik olarak y'ye ve boyuta göre x'i bulacaktır.

In [49]:
a = a.reshape(-1, 2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

- Yukarıda matrisin satir sayısını sütun sayısı=2'ye göre ayarlamıştır

### Matrise Yeni Bir Boyut Eklemek

In [50]:
xx = np.arange(1,11)
xx

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
xx.shape

(10,)

In [52]:
xx = xx[np.newaxis, :]

In [53]:
xx.shape

(1, 10)

In [54]:
xx = np.arange(1,11)

In [55]:
xx = xx[:, np.newaxis]

In [56]:
xx.shape

(10, 1)

In [57]:
xx = np.arange(1,11)

In [58]:
xx = xx[None, :]
xx

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [59]:
xx.size

10

## Array'lerde Concatenation

- iki tane arrayi birleştirirken np.concatenate() fonksiyonunu kullanrız.

In [60]:
a = np.array([1,2,3,4])

In [61]:
b = np.array([5,6,7,8])

In [62]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

- python listlerini de arrayleri ile birleştirebiliriz.

In [63]:
l = [10,11]

In [64]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

- fakat listede hem int hemde float eleman varsa arraylerin elemanlarını float yapacaktır.
- veya listede str varsa arrayin elemanlarını da str yapar.

In [65]:
l = [10, 11, 11.2]

In [66]:
np.concatenate([a,b,l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. , 10. , 11. , 11.2])

- eğer ki np.concatenate([x,y], axis=1) olarak bir input verecek olursak;

In [67]:
x = np.array([[1,2,3],[4,5,6]])

In [68]:
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [69]:
np.concatenate([x,x], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- burada axis = 0 (default deger) alt alta ekleyecektir. 
- Fakat axis = 1 dersek, yanyana koyacaktir.

## Stack

- Stack, yeni boyut ekleyip o boyut üzerinde concatenation yapabildiğimiz senaryodur

In [70]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [71]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
np.stack([a,b], axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## Splitting

- np.list bir listeyi veya array'i bolmek için kullanırız.
- np.list(input, [bolunecek_yer, bolunecek_yer])

In [73]:
l = [10, 20, 30, 40, 50, 60, 70, 80]

In [74]:
np.split(l, [2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [75]:
np.split(l, [3, 5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

In [76]:
np.split(l, [2,4,6])

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]

- ayrıca parcalanan bu elemanları bir degerlere atayabiliriz. 

In [77]:
a,b,c,d = np.split(l, [2,4,6])
print("a: ", a)
print("b: ", b)
print("c: ", c)
print("d: ", d)

a:  [10 20]
b:  [30 40]
c:  [50 60]
d:  [70 80]


### vsplit

-vertical split

In [78]:
a = np.arange(20).reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [79]:
np.vsplit(a, [1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

### hsplit

- horizontal split

In [80]:
a = np.arange(20).reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [81]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [82]:
np.hsplit(a, [2])[0]

array([[ 0,  1],
       [10, 11]])

In [83]:
np.hsplit(a, [2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [84]:
a = np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## Sorting

- array'leri sıralamak için kullanırız
- bunu iki farkli sekilde yapabiliriz.
- np.sort(x) inplace degildir, yani mecvut arrayi güncellemez.
- x.sort() ise inplacedir, yani x arrayini de günceller.

In [85]:
aa = np.array([20, 32, 5, 30, 10])
aa

array([20, 32,  5, 30, 10])

In [86]:
np.sort(aa)
aa

array([20, 32,  5, 30, 10])

In [87]:
aa.sort()
aa

array([ 5, 10, 20, 30, 32])

### argsort

- argsort bir arrayi sıraladıktan sonra o arrayin indexlerini verir.

In [88]:
idxs = np.argsort(aa)
idxs

array([0, 1, 2, 3, 4], dtype=int32)

## Indexing işlemi


### Fancy Indexing
- Fancy indexing ile bir kaç tane belirli indexteki elemanı döndürebiliriz.

In [89]:
x = np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
idxs = [4,5,7,11]

- 4, 5, 7 ve 11 indexlerindeki elemanları döndürmek istersek:

In [91]:
x[idxs] 

array([ 5,  6,  8, 12])

In [92]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
aa = np.arange(20).reshape(4,5)
aa

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [94]:
idx=[1,3,2]
idx2=[3,0,2]

- [ (1,3), (3,0), (2,2) ]

In [95]:
aa[idx, idx2]

array([ 8, 15, 12])

In [96]:
x = np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [97]:
x[[1,2,3]] = 20
x

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [98]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Subaray

In [99]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [100]:
b = a[:2,:3]
b

array([[1, 2, 3],
       [5, 6, 7]])

In [101]:
b[0,0] = 100

In [102]:
b

array([[100,   2,   3],
       [  5,   6,   7]])

In [103]:
a

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

### Copy()
- Copy() methodu ile subarray'in degerini degistirmeden farkli bir array yaratabiliriz.

In [104]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [105]:
b = a[:2,:3].copy()
b

array([[1, 2, 3],
       [6, 7, 8]])

In [106]:
b[0,0] = 100
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [107]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Conditional Indexing

In [108]:
a = np.arange(1,10)

- bu arrayin içinde 5'ten kücük olan degerleri almak istersek

In [109]:
a<5

array([ True,  True,  True,  True, False, False, False, False, False])

In [110]:
a[a<5]

array([1, 2, 3, 4])

- veya:

In [111]:
filt = a < 3
a[filt]

array([1, 2])

In [112]:
b = np.array([2,3,3,4,5,61,7,8,9])
b

array([ 2,  3,  3,  4,  5, 61,  7,  8,  9])

In [113]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
a[a==b]

array([3, 4, 5, 7, 8, 9])

In [115]:
xx = np.arange(1,50,2)
xx

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [116]:
filter_x = (xx < 20) | (xx > 35)

In [117]:
xx[filter_x]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 37, 39, 41, 43, 45, 47, 49])

- bir filtrenin tersini almak istersek ~ kullanırız

In [118]:
xx[~filter_x]

array([21, 23, 25, 27, 29, 31, 33, 35])

### Multidimension array'lerde conditional indexing:

In [119]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [120]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

## Sum methodu
- bir array'deki değerlerin toplamını bulmak için kullanırız.

In [122]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [123]:
np.sum(a)

210

- bu toplama işlemine filtre de ekleyebiliriz.

In [124]:
filtre = a<5

In [125]:
np.sum(filtre)

4

- bu şekilde filtreye uyan kaç adet değerimiz olduğunu buluruz.

In [126]:
np.sum(a[filtre])

10

- filtreye uyan değerlerin toplamını bulmak istersek de üstteki şekilde ulaşabiliriz.


In [127]:
filtre = (a<5) | (a>9)

In [128]:
np.sum(a[filtre])

175

### Belirli axis'ler üzerinde toplama:
- axis = 0 ve 1 diyerek sadece satır veya sutunlar üzerinde toplama yapabiliriz.

In [129]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [130]:
np.sum(a, axis=0)

array([34, 38, 42, 46, 50])

In [131]:
np.sum(a, axis=1)

array([15, 40, 65, 90])

## All methods
- All methodu, verilen şartı array'in bütün elemanları sağlayıp sağlamadığını kontrol etmek için kullanılır.

In [135]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [136]:
np.all(a > -1)

True

In [137]:
np.all(a>5)

False

- axis = 1 satırlar üzerinde şart aranır

In [140]:
np.all(a>-1, axis=1)

array([ True,  True,  True,  True,  True])

- axis = 0 ise sütunlar üzeridne şartlar aranır

In [142]:
np.all(a>5, axis=0)

array([False, False, False, False, False])

## Any methods
- Any methodu, verilen şartı array'in herhangi bir elemanı sağlayıp sağlamadığını kontrol etmek için kullanılır.

In [144]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [143]:
np.any(a>15)

True

In [145]:
np.any(a>17, axis = 0)

array([False, False, False,  True,  True])

In [146]:
np.any(a>17, axis=1)

array([False, False, False,  True])